acf-core:
    permission_denied: "&7[&5AlpineClientAPI&7] &fYou do not have permission to execute this command."
    permission_denied_parameter: "&7[&5AlpineClientAPI&7] &fYou do not have permission to execute this command."
    error_generic_logged: "&7[&4AlpineClientAPI&7] &fAn error occurred while performing this command."
    unknown_command: "&7[&5AlpineClientAPI&7] &fUnknown sub-command. Use '&7/help&8'&f for a list of commands."
    invalid_syntax: "&7[&5AlpineClientAPI&7] &dUsage: &f{command} &7{syntax}"
    error_prefix: "&7[&4AlpineClientAPI&7] &cError:&f {message}"
    error_performing_command: "&7[&4AlpineClientAPI&7] &fAn error occurred while performing this command."
    info_message: "{message}"
    please_specify_one_of: "&7[&4AlpineClientAPI&7] &cError:&f Please specify a valid option"
    must_be_a_number: "&7[&4AlpineClientAPI&7] &cError:&f {num} must be a number"
    must_be_min_length: "&7[&4AlpineClientAPI&7] &cError:&f Value must be at least {min} characters long"
    must_be_max_length: "&7[&4AlpineClientAPI&7] &cError:&f Value must be at most {max} characters long"
    please_specify_at_most: "&7[&4AlpineClientAPI&7] &cError:&f Please specify a value at most {max}"
    please_specify_at_least: "&7[&4AlpineClientAPI&7] &cError:&f Please specify a value at least {min}"
    not_allowed_on_console: "&7[&4AlpineClientAPI&7] &cError:&f Console may not execute this command"
    could_not_find_player: "&7[&4AlpineClientAPI&7] &cError:&f Could not find a player by the name &c{search}"
    no_command_matched_search: "&7[&5AlpineClientAPI&7]&f No command matched '&7{search}&f'"
    help_page_information: "   &7&l* &rPage &d{page}/{totalpages} &8[&7{results} results&8]"
    help_no_results: "&7[&4AlpineClientAPI&7] &cError:&f No more results were found"
    help_header: "&7[&5AlpineClientAPI&7] &dHelp: {commandprefix}{command}&r"
    help_format: "   &7&l* &d{command} &7{parameters}&r: {description}"
    help_detailed_header: "&7[&5AlpineClientAPI&7] &dHelp: {commandprefix}{command}&r"
    help_detailed_command_format: "   &7&l* &d{command} &7{parameters}&r: {description}"
    help_detailed_parameter_format: "   &7&l* &d{syntaxorname}&r: {description}"
    help_search_header: "&7[&5AlpineClientAPI&7] &dHelp: {commandprefix}{command}&r"

acf-minecraft:
    invalid_world: "&7[&4AlpineClientAPI&7] &cError:&f That world does not exists."
    you_must_be_holding_item: "&7[&4AlpineClientAPI&7] &cError:&f You must be holding an item in your main hand."
    player_is_vanished_confirm:
        - "&7[&5AlpineClientAPI&7] &d{vanished}&f is vanished. Don't blow their cover!"
    username_too_short: "&7[&4AlpineClientAPI&7] &cError:&f Username too short, must be at least three characters"
    is_not_a_valid_name: "&7[&4AlpineClientAPI&7] &cError:&f {name} is not a valid username"
    multiple_players_match: "&7[&4AlpineClientAPI&7] &cError:&f Multiple players matched {search}, please be more specific"
    no_player_found_server: "No player matching {search} is connected to this server"
    no_player_found_offline: "No player matching {search} could be found"
    no_player_found: "No player matching {search} could be found"
    location_please_specify_world: "&7[&4AlpineClientAPI&7] &cError:&f Please specify a valid world"
    location_please_specify_xyz: "&7[&4AlpineClientAPI&7] &cError:&f Please specify the coordinates x, y and z"
    location_console_not_relative: "&7[&4AlpineClientAPI&7] &cError:&f Console may not use relative coordinates for location"